apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformDisks.fullname" . }}
  labels: {{ include "platformDisks.labels.standard" . | nindent 4 }}
    service: platform-disks
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "platformDisks.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "platformDisks.selectorLabels" . | nindent 8 }}
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets}}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end}}
      containers:
      - name: platform-disks
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: tcp-web
            protocol: TCP
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        env:
          {{- include "platformDisks.env" . | nindent 10 }}
        volumeMounts:
        - mountPath: {{ include "platformDisks.kubeAuthMountRoot" . }}
          name: kube-api-data
          readOnly: true

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
      - name: kube-api-data
        projected:
          sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
