apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platformDisks.fullname" . }}
  labels: {{ include "platformDisks.labels.standard" . | nindent 4 }}
    service: platform-disks
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "platformDisks.name" . }}
      release: {{ .Release.Name }}
      service: platform-disks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "platformDisks.name" . }}
        release: {{ .Release.Name }}
        service: platform-disks
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets}}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end}}
      containers:
      - name: platform-disks
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: tcp-web
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
          - containerPort: 8080
            name: tcp-web
            protocol: TCP
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        env:
        - name: NP_DISK_API_PLATFORM_AUTH_URL
          value: {{ .Values.platform.authUrl | quote }}
        - name: NP_DISK_API_PLATFORM_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 10 }}
{{- end }}
        - name: NP_DISK_API_K8S_API_URL
          value: https://kubernetes.default:443
        - name: NP_DISK_API_K8S_AUTH_TYPE
          value: token
        - name: NP_DISK_API_K8S_CA_PATH
          value: {{ include "platformDisks.kubeAuthMountRoot" . }}/ca.crt
        - name: NP_DISK_API_K8S_TOKEN_PATH
          value: {{ include "platformDisks.kubeAuthMountRoot" . }}/token
        - name: NP_DISK_API_K8S_NS
          value: {{ .Values.disks.namespace | default "default" | quote }}
        {{- if .Values.disks.storageClassName }}
        - name: NP_DISK_API_K8S_STORAGE_CLASS
          value: {{ .Values.disks.storageClassName }}
        {{- end }}
        - name: NP_DISK_API_STORAGE_LIMIT_PER_PROJECT
          value: {{ .Values.disks.limitPerProject | quote }}
        - name: NP_DISK_API_ENABLE_DOCS
          value: {{ .Values.docs.enabled | quote }}
        - name: NP_CLUSTER_NAME
          value: {{ .Values.platform.clusterName | quote }}
        {{- if .Values.cors.origins }}
        - name: NP_CORS_ORIGINS
          value: {{ join "," .Values.cors.origins | quote }}
        {{- end }}
        {{- if .Values.zipkin }}
        - name: NP_ZIPKIN_URL
          value: {{ .Values.zipkin.url }}
        - name: NP_ZIPKIN_SAMPLE_RATE
          value: {{ .Values.zipkin.sampleRate | default 0 | quote }}
        {{- end }}
        {{- if .Values.sentry }}
        - name: NP_SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: NP_SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: NP_SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
        volumeMounts:
        - mountPath: {{ include "platformDisks.kubeAuthMountRoot" . }}
          name: kube-api-data
          readOnly: true

      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
      - name: kube-api-data
        projected:
          sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
