apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "platformDisks.fullname" . }}
  namespace: {{ .Values.disks.namespace }}
  labels: {{ include "platformDisks.labels.standard" . | nindent 4 }}
    service: platform-disks
rules:
- apiGroups:
  - "neuromation.io"
  resources:
  - disknamings
  verbs:
  - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "platformDisks.fullname" . }}
  namespace: {{ .Values.disks.namespace }}
  labels: {{ include "platformDisks.labels.standard" . | nindent 4 }}
    service: platform-disks
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "platformDisks.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
