apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformDisks.fullname" . }}
  labels: {{ include "platformDisks.labels.standard" . | nindent 4 }}
    service: disks
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_DISK_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: tcp-web
  selector:
    app: {{ include "platformDisks.name" . }}
    release: {{ .Release.Name }}
    service: disks
