NP_DISK_PROVIDER: "aws"  # "aws", "gcp" or "azure"
NP_DISK_API_PLATFORM_AUTH_URL: http://platformauthapi:8080
NP_DISK_API_K8S_NS: default
NP_DISK_API_K8S_STORAGE_CLASS_NAME: storage-class-disks
NP_DISK_API_ENABLE_DOCS: "false" # "true" or "false"
NP_DISK_API_STORAGE_LIMIT_PER_USER: "536870912000"  # In bytes, 500 gb
NP_CLUSTER_NAME: ""

image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

platform:
  token: {}

resources:
  requests:
    cpu: "0.1"
    memory: "150Mi"
  limits:
    cpu: "0.3"
    memory: "300Mi"

ingress:
  enabled: false

secrets: []

zipkin: {}

sentry: {}
