apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: disknamings.neuromation.io
spec:
  group: neuromation.io
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              disk_id:
                type: string
    additionalPrinterColumns:
    - name: DiskNaming
      type: string
      jsonPath: .spec.disk_id
  scope: Namespaced
  names:
    kind: DiskNaming
    listKind: DiskNamingsList
    plural: disknamings
    singular: disknaming
    shortNames: []
