apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: disknamings-admin
  namespace: {{ .Values.disks.namespace }}
rules:
- apiGroups:
  - "neuromation.io"
  resources:
  - disknamings
  verbs:
  - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: disknamings-admin
  namespace: {{ .Values.disks.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: disknamings-admin
  apiGroup: rbac.authorization.k8s.io
