apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformdiskapiwatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      service: platformdiskapiwatcher
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: platformdiskapiwatcher
    spec:
      {{- if .Values.imagePullSecrets}}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end}}
      containers:
      - name: platformdiskapi
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        {{- end }}
        command: ["platform-disk-api-watcher"]
        env:
        - name: NP_DISK_API_K8S_API_URL
          value: https://kubernetes.default:443
        - name: NP_DISK_API_K8S_AUTH_TYPE
          value: token
        - name: NP_DISK_API_K8S_CA_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NP_DISK_API_K8S_TOKEN_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: NP_DISK_API_K8S_NS
          value: {{ .Values.disks.namespace | default "default" | quote }}
        {{- if .Values.zipkin }}
        - name: NP_ZIPKIN_URL
          value: {{ .Values.zipkin.url }}
        - name: NP_ZIPKIN_SAMPLE_RATE
          value: {{ .Values.zipkin.sampleRate | default 0 | quote }}
        {{- end }}
        {{- if .Values.sentry }}
        - name: NP_SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        - name: NP_SENTRY_CLUSTER_NAME
          value: {{ .Values.sentry.clusterName }}
        - name: NP_SENTRY_SAMPLE_RATE
          value: {{ .Values.sentry.sampleRate | default 0 | quote }}
        {{- end }}
