image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

disks:
  namespace: platform-jobs
  limitPerProject: "536870912000" # In bytes, 500 gb

  # Default storage class is used if null or empty.
  storageClassName: null

platform:
  clusterName: ""
  authUrl: ""
  token: {}

docs:
  enabled: ""

resources:
  requests:
    cpu: "0.1"
    memory: "150Mi"
  limits:
    cpu: "0.3"
    memory: "300Mi"

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

cors: {}

secrets: []

zipkin: {}

sentry:
  dsn: ""
  clusterName: ""
  sampleRate: 0.002

priorityClassName: ""


jobProjectNamespaceMigration:
  schedule: "*/5 * * * *" # every 5 minutes
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"
