image:
  repository: "$IMAGE_REPO"
  tag: "$IMAGE_TAG"

imagePullSecrets: []

replicas: 2

disks:
  namespace: default
  limitPerUser: "536870912000" # In bytes, 500 gb

  # Default storage class is used if null or empty.
  storageClassName: null

platform:
  clusterName:
  authUrl:
  token: {}

docs:
  enabled: true

resources:
  requests:
    cpu: "0.1"
    memory: "150Mi"
  limits:
    cpu: "0.3"
    memory: "300Mi"

ingress:
  enabled: false
  ingressClassName: ""
  hosts: []
  annotations: {}

service:
  annotations: {}

cors: {}

secrets: []

zipkin: {}

sentry: {}

priorityClassName: ""
