name: CI

on:
  push:
    branches: [master]
    tags: [v*.*, v*.*.*]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: All checks are passed
    uses: ./.github/workflows/test.yaml

  release:
    name: Create release
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: neuro-inc/reuse/.github/workflows/release-service.yaml@v25.4.0
    with:
      image: platformdiskapi
      helm_charts: platform-disks

  deploy:
    name: Deploy
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: neuro-inc/reuse/.github/workflows/deploy-service.yaml@v25.4.0
    secrets:
      tf_api_token: ${{ secrets.TF_API_TOKEN }}
    with:
      environment: dev
      dev_workspace: ${{ vars.DEV_TFC_WORKSPACE_JSON }}
      variables: |
        platform_disks_version=${{ needs.release.outputs.version }}
